sudo: false
language: cpp
compiler: clang
matrix:
  include:
  - os: linux
    env: OS=ubuntu EASY_BUILD=x64
  - os: linux
    env: OS=ubuntu EASY_BUILD=arm
  - os: linux
    env: OS=ubuntu EASY_BUILD=hosted
  - os: osx
    env: OS=osx EASY_BUILD=x64
  exclude:
    - os: linux
    - compiler: clang
script:
  - ./easy_build_$EASY_BUILD.sh nosudo $OS
  - ./tests/testsuite.sh
  - ./scripts/runtest.py
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qemu; fi
install: true
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#pedigree
    template:
    - ! '%{repository}/%{branch} (%{commit} - %{author}): %{message}'
    - ! 'Build details: %{build_url}'
    on_success: change
    on_failure: always
  slack:
    secure: T9GJHictl8hUOgGh5RRVmRMExqlWJByssoSYdgnFuHA8ugLXyvHyYaVjLPVcFE9yv7w+sQgki0ZIzCyUH/Hg6/UPwRaH8W4Cm57vQwhE+TUvfy6eRRvYT118X/9X3xkYwhNUks+uydP6oI9YTnvr1XrzB6L4htA7Ma/YKBDhLhg=
addons:
  apt:
    packages:
      - libmpfr-dev
      - libmpc-dev
      - libgmp3-dev
      - sqlite3
      - texinfo
      - scons
      - xorriso
      - e2fsprogs
      - qemu
      - nasm
      - uboot-mkimage
      - clang
      - valgrind
cache:
  directories:
  - $HOME/.ccache
  - $HOME/pedigree-compiler
